version: '3.8'

services:
  counter-service:
    build:
      context: https://github.com/shirtzo/TaseExamAnsibleDocker.git
      dockerfile: /home/ec2-user/TaseExamAnsibleDocker/counter-service/Dockerfile
    container_name: counter-service
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    networks:
      - my-network

  web-service:
    build:
      context: https://github.com/shirtzo/TaseExamAnsibleDocker.git
      dockerfile: /home/ec2-user/TaseExamAnsibleDocker/web-service/Dockerfile
    container_name: web-service
    ports:
      - "3000:3000"
    depends_on:
      - counter-service
    networks:
      - my-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:

volumes:
  pg_data:
