version: '3.8'

services:
  counter-service:
    image: shirtzo/counter-service:1.0.7
    container_name: counter-service
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  web-service:
    image: shirtzo/web-service:1.0.5
    container_name: web-service
    ports:
      - "3000:3000"
    depends_on:
      - counter-service

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt