- name: Cleanup Docker and remove all related components
  hosts: all
  become: yes

  vars:
    containers_to_remove:
      - web-service
      - counter-service
      - postgres

  vars_files:
    - vars.yaml

  tasks:
    - name: Stop and remove chosen  containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ containers_to_remove }}"

    - name: Remove Docker leftovers (images, containers, volumes, networks)
      command: docker system prune -af

    - name: Remove Docker Compose file
      file:
        path: "{{ compose_file_dest }}/docker-compose.yaml"
        state: absent

        - name: Uninstall Docker Compose
      file:
        path: "{{ compose_package_dest }}"
        state: absent

    - name: Uninstall Docker (if installed)
      package:
        name: docker
        state: absent