---
- name: Deploy Docker Compose application from public GitHub repository
  hosts: all
  become: yes

  vars:
    compose_file_url: "https://raw.githubusercontent.com/Haxxnet/Compose-Examples/main/examples/code-server/docker-compose.yml"
    compose_file_dest: "/home/ec2-user"
    compose_version: "v2.29.2"
    compose_package_url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    compose_package_dest: "/usr/local/bin/docker-compose"

  tasks:
    - name: Install Docker (if not installed already)
      package:
        name: docker
        state: present

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose using GitHub
      get_url:
        url: "{{ compose_package_url }}"
        dest: "{{ compose_package_dest }}"
        mode: '0755'

    - name: Download docker-compose.yml from GitHub
      get_url:
        url: "{{ compose_file_url }}"
        dest: "{{ compose_file_dest }}"
        mode: '0644'

    - name: Run docker compose up in a specific directory
      command: docker-compose up -d
      args:
        chdir: "{{ compose_file_dest }}"